# Generated by Django 6.0 on 2026-01-23 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_post_post_type_alter_comment_id_alter_reaction_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('letter', 'Letter'), ('poem', 'Poem'), ('thought', 'Thought'), ('confession', 'Confession'), ('apology', 'Apology'), ('unsent', 'Unsent'), ('note', 'Note')], default='thought', max_length=20),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('spam', 'Spam'), ('hate', 'Hate Speech'), ('harassment', 'Harassment'), ('inappropriate', 'Inappropriate Content'), ('other', 'Other')], default='spam', max_length=100)),
                ('session_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='core.post')),
            ],
        ),
    ]
