# Generated by Django 6.0 on 2026-01-25 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_comment_id_alter_post_post_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_analyzed',
            field=models.BooleanField(default=False),
        ),
    ]
